# Generated by Django 4.2.1 on 2023-05-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carga_horaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(default='', max_length=50)),
                ('Asginaturas', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
