# Generated by Django 4.2.1 on 2023-05-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_rename_ciudad_ciudad_nombre_and_more'),
        ('academico', '0002_apartamento_torre_delete_carga_horaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='torre',
            name='id_Domicilio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.domicilio'),
            preserve_default=False,
        ),
    ]
