# Generated by Django 4.2.1 on 2023-05-23 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('matriculas', '0001_initial'),
        ('academico', '0004_delete_apartamento_delete_torre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('estado_grado', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('estado_curso', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.CharField(default='', max_length=50)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('estado_asignatura', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.CharField(default='', max_length=50)),
                ('id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_estudiante',
            fields=[
                ('id_curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academico.cursos')),
                ('estado_lista_estudiante', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.CharField(default='', max_length=50)),
                ('id_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.matricula')),
                ('id_usuario_director_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario')),
            ],
        ),
    ]
