# Generated by Django 4.2.1 on 2023-05-23 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
        ('usuario', '0001_initial'),
        ('academico', '0006_carga_horaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notas_estudiantes_curso',
            fields=[
                ('id_carga_horaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='academico.carga_horaria')),
                ('Nota', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.CharField(default='', max_length=50)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
                ('id_lista_estdiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matriculas.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id_usuario_jefe_area', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuario.usuario')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.CharField(default='', max_length=50)),
                ('estado_area', models.CharField(default='', max_length=50)),
                ('id_asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.asignatura')),
            ],
        ),
    ]
