# Generated by Django 4.2.1 on 2023-05-22 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='', max_length=50)),
                ('indicativo', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.CharField(default='', max_length=50)),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(default='', max_length=50)),
                ('codigo_postal', models.CharField(default='', max_length=50)),
                ('barrio', models.CharField(default='', max_length=50)),
                ('fecha_creacion', models.CharField(default='', max_length=50)),
                ('id_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.estado'),
        ),
    ]
