# Generated by Django 4.2.1 on 2023-05-22 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personal', '0002_ciudad_estado_domicilio_ciudad_id_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='ciudad',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='domicilio',
            old_name='direccion',
            new_name='Nombre',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
