# Generated by Django 4.2.1 on 2023-05-23 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('personal', '0003_rename_ciudad_ciudad_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario'),
        ),
    ]
