# Generated by Django 4.2.1 on 2023-05-23 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_domicilio_id_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ciudad',
            old_name='Nombre',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='domicilio',
            old_name='Nombre',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='pais',
            old_name='Nombre',
            new_name='pais',
        ),
    ]
