# Generated by Django 4.2.1 on 2023-05-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='grado',
            field=models.CharField(default='', max_length=50),
        ),
    ]
